dependencies:
  - ssh
  - sudo
  - role: jnv.unattended-upgrades
    when: ansible_os_family == "Debian"
    become: yes
    unattended_automatic_reboot: true
    unattended_remove_unused_dependencies: true
    unattended_mail: "{{ ansible_user }}"
    unattended_origins_patterns:
      - origin=Debian,codename=${distro_codename}
      - label=Debian-Security
  - apps
  - oh-my-zsh
  - dotfiles
  - autojump
  - antibody
  - asdf
  - gpg
  - aws
  - git
