---
- name: install apache
  apt:
    name: apache2
- name: enable apache ssl module
  become: yes
  apache2_module:
    name: ssl
- name: enable apache rewrite module
  become: yes
  apache2_module:
    name: rewrite
- name: enable apache proxy module
  become: yes
  apache2_module:
    name: proxy
- name: enable apache proxy_http module
  become: yes
  apache2_module:
    name: proxy_http
- name: clone site repository
  become: yes
  git:
    repo: https://github.com/ShepherdJerred/apache-nas
    dest: /etc/apache2/sites-available
- name: enable site (http)
  become: yes
  command: a2ensite nas
- name: enable site (https)
  become: yes
  command: a2ensite nas-ssl
- name: restart apache2 service
  become: yes
  systemd:
    name: apache2
    enabled: yes
    state: restarted
- name: copy .htpasswd
  become: yes
  copy:
    src: files/.htpasswd
    dest: /etc/apache2/.htpasswd
    owner: root
    group: root
    mode: '755'
- name: install certbot packages
  apt:
    name:
      - certbot
      - python-certbot-apache
      - python3-certbot-dns-route53
- name: copy aws credentials
  become: yes
  copy:
    src: files/credentials
    dest: /root/.aws/credentials
    owner: root
    group: root
    mode: '600'
- name: run certbot
  become: yes
  command: certbot -n --agree-tos -m shepherdjerred@gmail.com --installer apache --dns-route53 -d nas.shepherdjerred.com
  register: certbot_output
