---
- name: install certbot packages
  become: yes
  package:
    name:
      - certbot
      - python-certbot-apache
      - python3-certbot-dns-route53
- name: create .aws directory for root
  become: yes
  file:
    path: /root/.aws
    state: directory
- name: copy aws credentials
  become: yes
  copy:
    src: files/credentials
    dest: /root/.aws/credentials
    owner: root
    group: root
    mode: '600'
- name: run certbot
  become: yes
  command: certbot -n --agree-tos -m shepherdjerred@gmail.com --installer apache --dns-route53 -d nas.home.shepherdjerred.com
  register: certbot_output
- name: install apache
  become: yes
  package:
    name: apache2
- name: enable apache ssl module
  become: yes
  apache2_module:
    name: ssl
- name: enable apache rewrite module
  become: yes
  apache2_module:
    name: rewrite
- name: enable apache proxy module
  become: yes
  apache2_module:
    name: proxy
- name: enable apache proxy_http module
  become: yes
  apache2_module:
    name: proxy_http
- name: copy nas.conf site
  become: yes
  copy:
    src: "files/nas/nas.conf"
    dest: "/etc/apache2/sites-available"
    owner: root
    group: root
- name: copy nas-ssl.conf site
  become: yes
  copy:
    src: "files/nas/nas-ssl.conf"
    dest: "/etc/apache2/sites-available"
    owner: root
    group: root
- name: enable site (http)
  become: yes
  command: a2ensite nas
- name: enable site (https)
  become: yes
  command: a2ensite nas-ssl
- name: copy .htpasswd
  become: yes
  copy:
    src: files/.htpasswd
    dest: /etc/apache2/.htpasswd
    owner: root
    group: root
    mode: '755'
- name: restart apache2 service
  become: yes
  systemd:
    name: apache2
    enabled: yes
    state: restarted
