---
- hosts: macs
  roles:
    - macos
- hosts: servers
  roles:
    - common
- hosts: ec2
  roles:
    - ec2
- hosts: amongus
  roles:
    - amongus
- hosts: factorio
  roles:
    - factorio
- hosts: minecraft
  roles:
    - minecraft
- hosts: nas
  roles:
    - nas
