---
- hosts: macs
  roles:
    - role: geerlingguy.homebrew
      homebrew_installed_packages:
        - "asciinema"
        - "coreutils"
        - "asdf"
        - "autojump"
        - "bat"
        - "chezmoi"
        - "exa"
        - "fd"
        - "fpp"
        - "fzf"
        - "git"
        - "gnupg"
        - "htop"
        - "jq"
        - "pinentry-mac"
        - "qemu"
        - "reattach-to-user-namespace"
        - "tcl-tk"
        - "tig"
        - "tmux"
        - "tree"
        - "vim"
        - "wget"
        - "zsh"
        - "aws/tap/aws-sam-cli"
        - "koekeishiya/formulae/skhd"
        - "koekeishiya/formulae/yabai"
      homebrew_cask_apps:
        - "qlcolorcode"
        - "qlimagesize"
        - "qlmarkdown"
        - "qlstephen"
        - "qlvideo"
        - "quicklook-json"
        - "google-chrome"
        - "1password"
        - "adobe-creative-cloud"
        - "alfred"
        - "bartender"
        - "better-touch-tool"
        - "citra"
        - "daisy-disk"
        - "discord"
        - "bitz"
        - "docker"
        - "fantastical"
        - "gpg-suite"
        - "jetbrains-toolbox"
        - "league-of-legends"
        - "steam"
        - "loopback"
        - "lungo"
        - "mailmate"
        - "microsoft-office"
        - "minecraft"
        - "notion"
        - "numi"
        - "resilio-sync"
        - "spotify"
        - "sublime-text"
        - "telegram"
        - "texpad"
        - "transmit"
        - "iterm2"
      homebrew_taps:
        - "aws/tap"
        - "homebrew/bundle"
        - "homebrew/cask"
        - "homebrew/core"
        - "homebrew/services"
        - "koekeishiya/formulae"
        - "thoughtbot/formulae"
    - role: geerlingguy.mas
      mas_installed_apps:
        - { id: 824183456, name: "Affinity Photo (1.7.3)"}
        - { id: 924726344, name: "Deliveries (3.2.1)"}
        - { id: 1449412482, name: "Reeder (4.2.2)"}
- hosts: servers
  roles:
    - common
- hosts: factorio
  roles:
    - factorio
- hosts: minecraft
  roles:
    - minecraft
- hosts: nas
  roles:
    - sonarr
    - filebot
    - ansible-plex
    - ufw-plex
    - fstab
    - syncthing
    - ufw-syncthing
    - ansible-resilio-sync
    - ufw-resilio-sync
    - role: jnv.unattended-upgrades
      become: yes
      unattended_automatic_reboot: true
      unattended_remove_unused_dependencies: true
      unattended_mail: "{{ ansible_user }}"
      unattended_origins_patterns:
        - origin=Debian,codename=${distro_codename}
        - label=Debian-Security
        - site=linux-packages.resilio.com
        - site=downloads.plex.tv
        - site=get.filebot.net
        - site=apt.syncthing.net
    - apache
    - ufw-apache
