---
- hosts: nas
  remote_user: jerred
  vars_files:
    - vars/aws_credentials.yml
  roles:
    - sudo
    - role: ansible-secure-ssh
      become: yes
      ssh_user: jerred
      ssh_identity_key: files/id_rsa.pub
    - ufw
    - ansible-netdata
    - ansible-plex
    - ansible-resilio-sync
    - role: jnv.unattended-upgrades
      become: yes
      unattended_automatic_reboot: true
      unattended_remove_unused_dependencies: true
      unattended_mail: jerred
      unattended_origins_patterns:
        - origin=Debian,codename=${distro_codename}
        - label=Debian-Security
        - site=linux-packages.resilio.com
        - site=downloads.plex.tv
    - role: geerlingguy.apache
      become: yes
      apache_create_vhosts: false
      apache_remove_default_vhost: true
      apache_mods_enabled:
        - ssl.load
        - proxy.load
    - role: ssl
