---
- hosts: macs
  roles:
    - macos
- hosts: wsl
  roles:
    - wsl
- hosts: servers
  roles:
    - bootstrap
    - server
- hosts: amongus
  roles:
    - amongus
- hosts: factorio
  roles:
    - factorio
- hosts: minecraft
  roles:
    - minecraft
- hosts: nas
  roles:
    - nas
- hosts: hades
  roles:
    - hades