---
- hosts: nas
  remote_user: jerred
  roles:
    - sudo
    - role: ansible-secure-ssh
      become: yes
      ssh_user: jerred
      ssh_identity_key: files/id_rsa.pub
    - zsh
    - oh-my-zsh
    - dotfiles
    - filebot
    - rust
    - exa
    - ufw
    - ansible-netdata
    - ansible-plex
    - fstab
    - ansible-resilio-sync
    - role: jnv.unattended-upgrades
      become: yes
      unattended_automatic_reboot: true
      unattended_remove_unused_dependencies: true
      unattended_mail: jerred
      unattended_origins_patterns:
        - origin=Debian,codename=${distro_codename}
        - label=Debian-Security
        - site=linux-packages.resilio.com
        - site=downloads.plex.tv
        - site=https://get.filebot.net/deb/
    - role: apache
    - role: ssl
