---
- src: https://github.com/vitalk/ansible-secure-ssh
- src: geerlingguy.apache
- src: geerlingguy.homebrew
- src: geerlingguy.mas
- src: jnv.unattended-upgrades
- src: https://www.github.com/mrlesmithjr/ansible-netdata
- src: https://github.com/Oefenweb/ansible-fail2ban
- src: elliotweiser.osx-command-line-tools
