---
- src: https://github.com/vitalk/ansible-secure-ssh
- src: geerlingguy.apache
- src: jnv.unattended-upgrades
- src: https://github.com/shepherdjerred/ansible-plex
- src: https://github.com/shepherdjerred/ansible-resilio-sync
- src: https://www.github.com/mrlesmithjr/ansible-netdata
- src: https://github.com/Oefenweb/ansible-fail2ban
