---
- src: https://github.com/vitalk/ansible-secure-ssh
- src: jnv.unattended-upgrades
- src: https://www.github.com/mrlesmithjr/ansible-netdata
- src: https://github.com/Oefenweb/ansible-fail2ban
- src: https://github.com/adriagalin/ansible.motd
- src: community.general
