- hosts: servers
  roles:
    - bootstrap
    - ufw
    - common
    - role: ansible-role-tailscale
      become: yes
      vars:
        legacy_apt_dependencies:
          - python3-apt
        tailscale_auth_key: "{{ tailscale_key }}"
    - role: ansible-fail2ban
      become: yes
      fail2ban_banaction: ufw
      when: ansible_os_family == "Debian"
    - role: ansible-netdata
      become: yes
    - role: ansible.motd
      become: yes
      vars:
        ag_motd_remove_default_config: yes
        ag_motd_info:
          - "Hostname: ": "{{ ansible_hostname }}"
          - "Distro: ": "{{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_distribution_release }}"
          - "Virtual Machine: ": "{{ 'YES' if ansible_virtualization_role == 'guest' else 'NO' }}"
          - "Processors: ": "{{ ansible_processor_vcpus }}"
          - "Memory: ": "{{ (ansible_memtotal_mb / 1000) | round(1) }}GB"
          - "Last Ansible run: ": "{{ ansible_date_time.iso8601 }}"
        ag_motd_content: |
          {% for item in ag_motd_info %}
          {% for key, value in item.items() | list %}
          {{ key }}{{ value }}
          {% endfor %}
          {% endfor %}
