#!/bin/bash
LABEL="ansible-password"
ACCOUNT_NAME="jerred"

if [ -f "/usr/bin/security" ]; then
  /usr/bin/security find-generic-password -w -a "$ACCOUNT_NAME" -l "$LABEL"
else
  echo "$VAULT_PASSWORD"
fi
