---
- name: clone dotfiles repository
  git:
    repo: https://github.com/shepherdjerred/dotfiles
    dest: "/home/{{ ansible_user }}/git/dotfiles"
- name: install stow
  become: yes
  apt:
    name: stow
