---
- name: install dependencies (CentOS)
  become: true
  when: ansible_os_family == "CentOS" or ansible_distribution == "Amazon" and ansible_distribution_version == "2"
  package:
    name:
      - readline # Python
      - openssl-devel # Ruby
      - readline-devel # Ruby
- name: install dependencies (Debian)
  when: ansible_os_family == "Debian"
  become: true
  package:
    name: libreadline-dev
- name: clone asdf repo
  git:
    repo: https://github.com/asdf-vm/asdf.git
    update: yes
    clone: true
    dest: "~/.asdf"
    depth: 1
- name: install java plugin
  shell:
    cmd: asdf plugin add java
    creates: ~/.asdf/plugins/java
  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ ansible_user }}/.asdf/bin/"
- name: install nodejs plugin
  shell:
    cmd: asdf plugin add nodejs
    creates: ~/.asdf/plugins/nodejs
  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ ansible_user }}/.asdf/bin/"
- name: install python plugin
  shell:
    cmd: asdf plugin add python
    creates: ~/.asdf/plugins/python
  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ ansible_user }}/.asdf/bin/"
- name: install ruby plugin
  shell:
    cmd: asdf plugin add ruby
    creates: ~/.asdf/plugins/ruby
  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ ansible_user }}/.asdf/bin/"
- name: install release team keys for node js
  shell: bash -c '~/.asdf/plugins/nodejs/bin/import-release-team-keyring'
- name: install previous release team keys for nodejs
  shell: bash -c '~/.asdf/plugins/nodejs/bin/import-previous-release-team-keyring'
- name: install asdf tools
  shell:
    cmd: asdf install
    chdir: "~"
  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ ansible_user }}/.asdf/bin/"
- name: reshim asdf
  shell:
    cmd: asdf reshim
  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ ansible_user }}/.asdf/bin/"
