---
- name: install ufw
  become: yes
  package:
    name: ufw
- name: whitelist ssh
  become: yes
  ufw:
    rule: allow
    name: ssh
- name: enable ufw
  become: yes
  ufw:
    state: enabled
    policy: deny
    direction: incoming
