---
- name: install sudo
  become: yes
  become_method: su
  package:
    name: sudo
- name: add wheel group
  become: yes
  become_method: su
  group:
    name: wheel
- name: add sudo group
  become: yes
  become_method: su
  group:
    name: sudo
- name: configure sudo
  become: yes
  become_method: su
  user:
    name: "{{ ansible_user }}"
    groups:
      - sudo
      - wheel
