---
- name: install sudo
  become: yes
  become_method: su
  package:
    name: sudo
- name: "add {{ ansible_user }} to group sudo"
  become: yes
  become_method: su
  when: ansible_os_family == "Debian"
  user:
    name: "{{ ansible_user }}"
    groups:
      - sudo
- name: "add {{ ansible_user }} to group wheel"
  become: yes
  become_method: su
  when: ansible_os_family == "CentOS"
  user:
    name: "{{ ansible_user }}"
    groups:
      - wheel
