---
- name: install sudo
  become: yes
  become_method: su
  package:
    name: sudo
- name: "add {{ ansible_user }} to group sudo"
  become: yes
  become_method: su
  when: ansible_os_family == "Debian"
  user:
    name: "{{ ansible_user }}"
    groups:
      - sudo
- name: "add {{ ansible_user }} to group wheel"
  become: yes
  become_method: su
  when: ansible_os_family == "CentOS"
  user:
    name: "{{ ansible_user }}"
    groups:
      - wheel
- name: "edit /etc/sudoers to allow group sudo"
  become: yes
  become_method: su
  when: ansible_os_family == "Debian"
  replace:
    path: /etc/sudoers
    regexp: \%sudo[ ]*ALL=\(ALL:ALL\) ALL
    replace: "sudo    ALL=(ALL:ALL) ALL"
