---
- name: install sudo
  become: yes
  become_method: su
  apt:
    name: sudo
- name: configure sudo
  become: yes
  become_method: su
  user:
    name: "{{ ansible_user }}"
    groups:
      - sudo
