- name: install applications
  become: yes
  package:
    update_cache: yes
    name:
      - shellcheck
      - exa
      - git
      - tree
      - vim
      - gnupg
      - zip
      - unzip
      - tmux
      - htop
