---
- name: install certbot packages
  apt:
    name:
      - certbot
      - python-certbot-apache
      - python3-certbot-dns-route53
- name: copy aws credentials
  become: yes
  copy:
    src: files/credentials
    dest: /root/.aws/credentials
    owner: root
    group: root
    mode: '600'
- name: run certbot
  become: yes
  command: certbot -n --agree-tos -m shepherdjerred@gmail.com --installer apache --dns-route53 -d nas.shepherdjerred.com
  register: certbot_output
- debug: msg="{{ certbot_output.stdout }}"
