---
- name: install dependencies
  become: yes
  package:
    name:
      - apt-transport-https
      - dirmngr
      - gnupg
      - ca-certificates
- name: install mono repostory key
  become: yes
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
- name: install mono repository
  become: yes
  apt_repository:
    repo: deb https://download.mono-project.com/repo/debian stable-buster main
- name: install mono
  become: yes
  package:
    name: mono-complete
