---
- name: "create user amongus"
  become: yes
  become_method: su
  user:
    name: amongus
- name: "add amongus to docker group"
  become: yes
  user:
    name: amongus
    groups:
      - docker
- name: create data directory
  become: yes
  file:
    path: /server/data
    state: directory
    group: amongus
    owner: amongus
- name: create plugins directory
  become: yes
  file:
    path: /server/data/plugins
    state: directory
    group: amongus
    owner: amongus
- name: create libraries directory
  become: yes
  file:
    path: /server/data/libraries
    state: directory
    group: amongus
    owner: amongus
- name: copy config.json
  become: yes
  copy:
    src: "files/amongus/config.json"
    dest: "/server/data/"
    owner: amongus
    group: amongus
- name: copy config.impostorCord.json
  become: yes
  template:
    src: "files/amongus/config.impostorCord.json"
    dest: "/server/data/"
    owner: amongus
    group: amongus
- name: copy update script
  become: yes
  copy:
    src: "files/amongus/update.sh"
    dest: "/server/data/"
    owner: amongus
    group: amongus
- name: copy systemd config
  become: yes
  copy:
    src: "files/amongus/docker.amongus.service"
    dest: "/etc/systemd/system"
    owner: root
    group: root
- name: enable docker.amongus.service
  become: yes
  systemd:
    name: docker.amongus.service
    state: restarted
    enabled: yes

